#!/usr/bin/env bash

# dehydrated-code-rack - easily invoke multiple dehydrated hooks

# Copyright (c) 2018 Mythic Beasts Ltd
# All right reserved

handler="$1"; shift

case $handler in
    deploy_challenge|clean_challenge)
        export DOMAIN="$1" TOKEN_FILENAME="$2" TOKEN_VALUE="$3"
        ;;
    deploy_cert|unchanged_cert)
        export DOMAIN="$1"
        export KEYFILE="$2" CERTFILE="$3" FULLCHAINFILE="$4" CHAINFILE="$5"
        export TIMESTAMP="$6" # not set for unchanged_cert
        ;;
    invalid_challenge)
        export DOMAIN="$1" RESPONSE="$2"
        ;;
    request_failure)
        export STATUSCODE="$1" REASON="$2" REQTYPE="$3"
        ;;
    exit_hook)
        ;;
    *)
        echo $0: unknown handler "'$handler'" >&2
        exit 1
        ;;
esac

dir=/etc/dehydrated/hooks/${handler//_/-}.d
/bin/mkdir -p $dir
/bin/run-parts $dir
