#!/bin/bash

ILO_CONF_DIR=/etc/dehydrated/hp-ilo

ILO_CONF_FILE="$ILO_CONF_DIR/$DOMAIN.ini"

# Check config file exists
if [ ! -f "$ILO_CONF_FILE" ]
then
  echo "No iLO configuration file for $DOMAIN (looked for $DOMAIN.ini in $ILO_CONF_DIR)" >&2
  exit 1
fi

# Sanity check connection is working by checking UID light status
if ! hpilo_cli -c "$ILO_CONF_FILE" "$DOMAIN" get_uid_status >/dev/null
then
  echo "Error checking connectivity to iLO (failed to get UID light status) for $DOMAIN" >&2
  exit 1
fi

# If that succeeded, request certificate
if ! hpilo_cli -c "$ILO_CONF_FILE" "$DOMAIN" certificate_signing_request country='$certificate.country' state='$certificate.state' locality='$certificate.locality' organization='$certificate.organization' organizational_unit='$certificate.organizational_unit' common_name="$DOMAIN" | grep -v '^>>>'
then
  echo "CSR request failed, retrying..." >&2
  # If request failed, assume iLO is still generating certificate and retry every 5 seconds for upto 10 minutes
  succeeded=0
  i=0
  while [ $i -lt 120 ]  # 120 * 5s waiting = 10 minutes
  do
    sleep 5
    if hpilo_cli -c "$ILO_CONF_FILE" "$DOMAIN" certificate_signing_request country='$certificate.country' state='$certificate.state' locality='$certificate.locality' organization='$certificate.organization' organizational_unit='$certificate.organizational_unit' common_name="$DOMAIN" 2>/dev/null | grep -v '^>>>'
    then
      # succeeded this time
      succeeded=1
      echo "Got CSR after $i re-attempts." >&2
      break
    fi
    i=$(( i + 1 ))
  done
  if [ $succeeded -eq 0 ]
  then
    echo "ERROR: unable to obtain CSR from iLO!" >&2
    exit 1
  fi
fi
